### ISSUE TITLE
DOCKER - Record scalability changes information in the scalability calendar

### ISSUE THREAD

**Issue by bussyjd** [Stacktical/stacktical-willitscale#33]
#### DESCRIPTION

When a DevOps user make a change to a service he wants to be able to log that change in his `Scalability Calendar` so he can track, observe or stage the scalability improvements and penalties.

#### ACCEPTANCE CRITERIA

* DevOps user is able to overview the previous changes on a timeline or a report
* DevOps user is able to input information concerning a scalability change
* DevOps user is able to verify the scalability improvements or degradations after a logged change
* DevOps user is able to share that logged change with his teammate and collaborate around it

**Comment by wilhempujar** [comment]
Issue moved to [Stacktical/stacktical-web-client #198](https://github.com/Stacktical/stacktical-web-client/issues/198) via [**ZenHub**](https://www.zenhub.com/)
